/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;

import java.awt.event.WindowEvent;
import java.util.HashMap;
import java.util.Observable;
import java.util.Observer;

import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

import controller.ClientManager;
import model.ActionType;
import model.Result;
import model.ResultCode;
import model.Room;
import model.ThreadNewFriend;
import model.ThreadNewRoom;
import model.User;

import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTable;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author ADMIN
 */
public class friendAddForm extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form friendAddForm
     */
	private DefaultTableModel dtm;
	ClientManager mCLientManager;
	ListForm mlistForm;
	FriendListForm p;
	private HashMap<String,ThreadNewFriend> listThread = new HashMap<String,ThreadNewFriend>();
    public friendAddForm(ListForm listform, ClientManager clientmanager,FriendListForm p, HashMap<String,ThreadNewFriend> listThread) {
    	initComponents();
    	mlistForm = listform;
    	mCLientManager= clientmanager;
        mCLientManager.addObserver(this);
        this.p=p;
        this.listThread = listThread;
        dtm = (DefaultTableModel)table.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btntimkiem(e);
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
          
        });
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Th\u00EAm b\u1EA1n m\u1EDBi");

        jLabel2.setText("T\u00EAn c\u1EA7n t\u00ECm ki\u1EBFm");

        jButton1.setText("T\u00ECm ki\u1EBFm");
        
        scrollPane = new JScrollPane();
        
        JButton btnNewButton = new JButton("K\u1EBFt b\u1EA1n");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		btnketban(e);
        	}
        });
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(185)
        					.addComponent(jButton1))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(27)
        					.addComponent(jLabel2)
        					.addGap(18)
        					.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, 289, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(39, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(140, Short.MAX_VALUE)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 175, GroupLayout.PREFERRED_SIZE)
        			.addGap(137))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(22, Short.MAX_VALUE)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 405, GroupLayout.PREFERRED_SIZE)
        			.addGap(25))
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(312, Short.MAX_VALUE)
        			.addComponent(btnNewButton)
        			.addGap(73))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(33)
        			.addComponent(jButton1)
        			.addGap(18)
        			.addComponent(scrollPane, GroupLayout.PREFERRED_SIZE, 286, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(btnNewButton)
        			.addContainerGap(38, Short.MAX_VALUE))
        );
        
        table = new JTable();
        table.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        			"ID","T\u00EAn", "Ng\u00E0y sinh", "Tu\u1ED5i", "Gi\u1EDBi t\u00EDnh"
        	}
        ));
        scrollPane.setViewportView(table);
        getContentPane().setLayout(layout);
        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void btntimkiem(ActionEvent e) {
		// TODO Auto-generated method stub
    	String name=jTextField1.getText();
    	dtm.setRowCount(0);
    	mCLientManager.getinfobyName(name,mCLientManager.mNickname);
	}
    protected void btnketban(ActionEvent e) {
    	int slt= table.getSelectedRow();
    	
    	int iduserSelected = Integer.parseInt(dtm.getValueAt(slt, 0).toString());
    	
    	mCLientManager.ketban(iduserSelected, mCLientManager.mNickname);
    	
    }
    @Override
	public void update(Observable o, Object arg) {
    	Result result =(Result)arg;
        if(result.mResultCode.equals(ResultCode.ERROR))
        {
            JOptionPane.showMessageDialog(null, result.mContent, "ThÃ¡ÂºÂ¥t bÃ¡ÂºÂ¡i", JOptionPane.ERROR_MESSAGE);
            return;
        }
        switch (result.mActionType) {
    	case ActionType.Get_User_Info_byName:
    	{
//    		DefaultTableModel dtm = (DefaultTableModel)table.getModel();
            if(result.mContent.length()>0)
            {
                //ds phÃƒÂ²ng cÃƒÂ³ dÃ¡ÂºÂ¡ng maphong<col>tenphong<col>songuoi<col><row>
                //                 maphong<col>tenphong<col>songuoi<col><row>
                String[] rows = result.mContent.split("<row>");
                for (int i = 0; i < rows.length; i++) //hÃƒÂ ng Ã„â€˜Ã¡ÂºÂ§u lÃƒÂ  trÃ¡Â»â€˜ng
                {
                    String[] cols = rows[i].split("<cols>");

                    dtm.addRow(cols);
                }
            }
            break;
    		}
    		
    }
        
	}
	protected void formWindowClosing(WindowEvent evt) {
		mCLientManager.deleteObserver(this);
		mCLientManager.addObserver(mlistForm);
		mlistForm.setVisible(true);
	}

	/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(friendAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(friendAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(friendAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(friendAddForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private JScrollPane scrollPane;
    private JTable table;
}
