package view;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;

import java.awt.event.WindowListener;
import java.util.HashMap;
import java.util.Observable;
import java.util.Observer;

import javax.swing.DefaultListModel;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JTabbedPane;
import javax.swing.JPanel;
import javax.swing.event.AncestorListener;
import javax.swing.table.DefaultTableModel;

import controller.ClientManager;
import model.ActionType;
import model.Result;
import model.ResultCode;
import model.Room;
import model.ThreadNewRoom;

import javax.swing.event.AncestorEvent;

/**
 *
 * @author ADMIN
 */
public class ListForm extends javax.swing.JFrame implements Observer {

    /**
     * Creates new form ListForm
     */
	 ClientManager mclientManager;
	 LoginForm loginForm;
	 private String createNameRoom = "";
	 private String findIDRoom = "";
	 private HashMap<String,ThreadNewRoom> listThread = new HashMap<String,ThreadNewRoom>();
	 private RoomListForm r;
	 
	
    public ListForm(ClientManager clientManager,LoginForm loginForm) {
        initComponents();
        this.mclientManager = clientManager;
        this.loginForm = loginForm;
        clientManager.addObserver(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            
            public void windowOpened(java.awt.event.WindowEvent evt) {
            	
            }
        });

        jButton1.setText("Thêm bạn");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Wjpu Lord");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/10207-man-student-light-skin-tone-icon-64.png")));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Change Profile", "Change Pass", "Logout" }));
        
        JButton createRoom = new JButton("Tạo phòng chat");
        
        JButton findRoom = new JButton("Tìm phòng chat");
        
        createRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	String s = (String)JOptionPane.showInputDialog(getContentPane(),"Nhap ten phong","Tao phong moi",JOptionPane.PLAIN_MESSAGE);
            	createNameRoom = s;
            	mclientManager.CreateRoom(s);
            }
        });
        
        findRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	String s = (String)JOptionPane.showInputDialog(getContentPane(),"Nhap id phong","Tim phong chat",JOptionPane.PLAIN_MESSAGE);
            	findIDRoom = s;
            	mclientManager.JoinRoom(s);
            }
        });
        
        
        
        
        
        
        tabbedPane = new JTabbedPane(JTabbedPane.TOP);
        
        tabbedPane.addAncestorListener(new AncestorListener() {
			
			@Override
			public void ancestorRemoved(AncestorEvent event) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void ancestorMoved(AncestorEvent event) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void ancestorAdded(AncestorEvent event) {
				FriendListForm p=new FriendListForm();
                tabbedPane.add(p,"danh sách bạn");
                r= new RoomListForm(mclientManager);
                tabbedPane.add(r,"danh sách phòng");
				
			}
		});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(29)
        					.addComponent(jButton1))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(tabbedPane, GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 96, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 115, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
        									.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(createRoom)
        									.addGap(18)
        									.addComponent(findRoom)))))))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(14)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 92, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 28, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jComboBox1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(createRoom)
        						.addComponent(findRoom))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(tabbedPane, GroupLayout.PREFERRED_SIZE, 390, GroupLayout.PREFERRED_SIZE)
        			.addGap(72)
        			.addComponent(jButton1)
        			.addContainerGap(36, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private JTabbedPane tabbedPane;
    
    
    
	@Override
	public void update(Observable o, Object arg) {

        Result result = (Result)arg;
        if(result.mResultCode.equals(ResultCode.ERROR))
        {
            JOptionPane.showMessageDialog(null, result.mContent, "Thất bại", JOptionPane.ERROR_MESSAGE);
            return;
        }
        switch (result.mActionType)
        {
            case ActionType.CREATE_ROOM:
            {
            	String[] lines = result.mContent.split(";", -1);
                ThreadNewRoom newThreadRoom = new ThreadNewRoom(new ChatGroupForm(mclientManager,lines[0],createNameRoom,1 ));
                newThreadRoom.run();;
                listThread.put(lines[0], newThreadRoom);
                r.setListModel(new Room(lines[0],createNameRoom,1,"null"));
                mclientManager.GetListRoom();
                break;
            }
            case ActionType.JOIN_ROOM:
            {
            	String[] lines = result.mContent.split(";", -1);
            	if(listThread.containsKey(findIDRoom)) listThread.remove(findIDRoom);
                ThreadNewRoom newThreadRoom = new ThreadNewRoom(new ChatGroupForm(mclientManager,findIDRoom,lines[0],Integer.parseInt(lines[1]) ));
                newThreadRoom.run();
                mclientManager.getMess(findIDRoom);
                mclientManager.GetListRoom();
                //r.setListModel(new Room(findIDRoom,lines[0],Integer.parseInt(lines[1])));
                break;
           }
            case ActionType.Close_WINDOW_CHAT:
            {
            	if (listThread.containsKey(result.mContent)) listThread.remove(result.mContent);
            }
        }   
	}

	
}
