/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import controller.ClientManager;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Observer;
import java.util.Observable;
import java.awt.event.ActionEvent;
import model.*;

/**
 *
 * @author ADMIN
 */
public class RegisterForm extends javax.swing.JFrame implements Observer{

    /**
     * Creates new form registerForm
     */
//	ClientManager mClientManager;
//    LoginForm mLogin;
//    public registerForm(LoginForm login, ClientManager clientManager) {
//        initComponents();
//        mLogin = login;
//        mClientManager = clientManager;
//        mClientManager.addObserver(this);
//    }
	ClientManager mClientManager;
    public RegisterForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnDangKy = new javax.swing.JButton();
        btnDangKy.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		jButtonRegisterPerformed(e);
        	}

			
        });
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUN = new javax.swing.JTextField();
        jPasswordFieldPass = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent evt) {
        		jButtonHuyPerformed(evt);
        	}			
        });
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldBirth = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox_nu = new javax.swing.JCheckBox();
        jTextFieldAge = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldFN = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldMN = new javax.swing.JTextField();
        jTextFieldLN = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnDangKy.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDangKy.setText("\u0110\u0103ng k\u00FD");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Chat App");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Password");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Quay lại");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel4.setText("Ng\u00E0y sinh");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Gi\u1EDBi t\u00EDnh");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel6.setText("Tu\u1ED5i");

        buttonGroup1.add(jCheckBox1);
        jCheckBox1.setSelected(true);
        jCheckBox1.setText("Nam");

        buttonGroup1.add(jCheckBox_nu);
        jCheckBox_nu.setText("N\u1EEF");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel7.setText("H\u1ECD");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel8.setText("T\u00EAn \u0111\u1EC7m");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel9.setText("T\u00EAn");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(188)
        			.addComponent(jLabel1)
        			.addContainerGap(201, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(23)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel7)
        								.addComponent(jLabel9))
        							.addGap(12))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel8)
        							.addGap(18)))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jTextFieldFN, GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
        						.addComponent(jTextFieldMN)
        						.addComponent(jPasswordFieldPass)
        						.addComponent(jTextFieldLN)))
        				.addComponent(jSeparator1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(24)
        					.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 66, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jTextFieldUN, 325, 325, 325))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(23)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(jLabel6)
        							.addGap(48))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel5)
        								.addComponent(jLabel4))
        							.addGap(18)))
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(btnDangKy)
        							.addPreferredGap(ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
        							.addComponent(jButton1)
        							.addGap(79))
        						.addGroup(layout.createSequentialGroup()
        							.addGroup(layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jTextFieldAge, GroupLayout.PREFERRED_SIZE, 100, GroupLayout.PREFERRED_SIZE)
        								.addGroup(layout.createSequentialGroup()
        									.addComponent(jCheckBox1)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(jCheckBox_nu)))
        							.addGap(0, 221, Short.MAX_VALUE))
        						.addComponent(jTextFieldBirth, 321, 321, 321))))
        			.addGap(39))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(23)
        			.addComponent(jLabel1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addGap(20)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextFieldUN, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
        			.addGap(34)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(jPasswordFieldPass, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(41)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(jTextFieldFN, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(40)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextFieldMN, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8))
        			.addGap(42)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel9)
        				.addComponent(jTextFieldLN, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jTextFieldBirth, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addGap(41)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel5)
        						.addComponent(jCheckBox1)
        						.addComponent(jCheckBox_nu))
        					.addGap(32)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel6)
        						.addComponent(jTextFieldAge, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(101))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(btnDangKy)
        						.addComponent(jButton1))
        					.addGap(31))))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
   
    private void jButtonRegisterPerformed(ActionEvent e) {
		// TODO Auto-generated method stub
		
    	//String message="";
    	
    	//if(jTextFieldUN.getText()!="")
    	try {
    		String Fname=jTextFieldFN.getText().trim();
    		String Mname=jTextFieldMN.getText().trim();
    		String Lname=jTextFieldLN.getText().trim();
    		String Birday=jTextFieldBirth.getText().trim();
    		int Age=Integer.parseInt(jTextFieldAge.getText());
    		String Uname=jTextFieldUN.getText().trim();
    		String Pass=String.valueOf(jPasswordFieldPass.getPassword());
    		String gender = "Nam";
    		if(jCheckBox_nu.isSelected()) {
    			gender="Nu";
    		}
    		 if(Fname.isBlank() || Mname.isBlank() || Lname.isBlank() || Birday.isBlank() || Uname.isBlank() || Pass.isBlank() ) {
    				JOptionPane.showMessageDialog(null, "vui lòng nhập đủ thông tin","Chưa nhập thông tin",JOptionPane.WARNING_MESSAGE);
    				jTextFieldFN.requestFocus();
    				jTextFieldMN.requestFocus();
    				jTextFieldLN.requestFocus();
    				jTextFieldBirth.requestFocus();
    				jTextFieldUN.requestFocus();
    				jPasswordFieldPass.requestFocus();
    				return;
    		 }
    		 if(mClientManager!=null)
    	        {
    	            mClientManager.Dispose();
    	        }    
    		ClientManager cm = new ClientManager(this);
    		cm.Register(Fname, Mname, Lname, Birday, Age, Uname, Pass, gender);
    		
    		if(!cm.isSuccessReg()) {
    			JOptionPane.showMessageDialog(null, "tên đăng nhập đã trùng");
    		}
    		else {
    			JOptionPane.showMessageDialog(null, "Đã đăng ký thành công");
    		}
		} catch (NumberFormatException e1) {
			JOptionPane.showMessageDialog(null, "vui lòng nhập đủ thông tin","Chưa nhập thông tin",JOptionPane.WARNING_MESSAGE);
		}
//		if(cm.isSuccessReg()) {
//			LoginForm mLogin=new LoginForm();
//	    	mLogin.setVisible(true);
//	    	mLogin.pack();
//	    	mLogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//	    	mLogin.setLocationRelativeTo(null);
//	        this.dispose();
//		}
	}
    private void jButtonHuyPerformed(ActionEvent evt) {
    	LoginForm mLogin=new LoginForm();
    	mLogin.setVisible(true);
    	mLogin.pack();
    	mLogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    	mLogin.setLocationRelativeTo(null);
        this.dispose();
	}	

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton btnDangKy;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox_nu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordFieldPass;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextFieldUN;
    private javax.swing.JTextField jTextFieldBirth;
    private javax.swing.JTextField jTextFieldAge;
    private javax.swing.JTextField jTextFieldFN;
    private javax.swing.JTextField jTextFieldMN;
    private javax.swing.JTextField jTextFieldLN;
    // End of variables declaration//GEN-END:variables
	@Override
	public void update(Observable o, Object arg) {
		// TODO Auto-generated method stub
		
	}
}
